- name: 星空下的YZY
  link: https://226yzy.com/
  feed: https://226yzy.com/atom.xml
  avatar: https://s4.ax1x.com/2021/12/11/oTDujJ.jpg
  
- name: 无影博客
  link: https://661111.github.io/
  feed: https://661111.github.io/atom.xml
  avatar: https://661111.github.io/images/avatar.png
  descr: 我是无影,主要更新blibli的几部沙雕动画.有时间会更别的东西
  
- name: Xhofe's Blog
  link: https://nn.ci/
  feed: https://nn.ci/atom.xml
  avatar: https://nn.ci/images/avatar.png
  descr: 晚来天欲雪，能饮一杯无？
  
- name: 零叁的个人博客
  link: https://blog.lingerbhw.cn/
  feed: https://blog.lingerbhw.cn/atom.xml
  avatar: https://status.lingerbhw.cn/upload/logo1.png?t=1662797253183
  descr: 我醉欲眠卿且去，明朝有意抱琴来  

- name: 零叁的个人博客
  link: https://blog.lingerbhw.cn/
  feed: https://blog.lingerbhw.cn/atom.xml
  avatar: https://status.lingerbhw.cn/upload/logo1.png?t=1662797253183
  descr: 我醉欲眠卿且去，明朝有意抱琴来    
